name: CI with Docker

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - name: 코드 가져오기
      uses: actions/checkout@v3

    - name: Python 설치
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: 의존성 설치
      run: |
        pip install -r requirements.txt

    - name: 코드 문법 체크
      run: |
        python -m py_compile main.py

    - name: Docker build 테스트
      run: |
        docker build -t my-app .